### ISSUE TITLE
PacMAP error

### ISSUE THREAD

**Issue by rxjx** [davisidarta/topometry#10]
I'm getting an error when trying to run this bit of code in Colab:

```
import topo as tp

tg = tp.TopOGraph()
tg.run_layouts(emb, n_components=2, bases=['diffusion', 'fuzzy'], graphs=['diff', 'fuzzy'], layouts=['MAP', 'PaCMAP'])
```

The error is:
`TypeError: PaCMAP.__init__() got an unexpected keyword argument 'n_dims'`

I can run pacMAP outside of topo just fine so this looks like an easy fix.

**Comment by davisidarta** [comment]
Hi @rxjx ! Thank you for your interest in TopOMetry :)

My apologies for the super late response.

I've pushed a fix to PyPI (v1.1.0). However, a new version of TopOMetry is also coming out this week with far fewer dependencies and a simplified API (v2.0.0).

Please do reopen this issue if your problem remains unsolved.
