### ISSUE TITLE
Conda Forge build

### ISSUE THREAD

**Issue by mfansler** [davisidarta/topometry#11]
FYI, I started [a PR to distribute this package through Conda Forge](https://github.com/conda-forge/staged-recipes/pull/23390). Conda Forge works downstream of PyPI, so there is nothing that needs to be done here to support this. Please let me know if you'd like to be included as a maintainer on the Conda recipe - it is entirely optional and updating is mostly automated anyway.

Thanks for this neat work!

**Comment by davisidarta** [comment]
Hi @mfansler ! Thank you for your interest and for the PR to distribute TopOMetry through Conda Forge! 

Please do include me as a maintainer on the Conda recipe :)
