### ISSUE TITLE
 module 'topo' has no attribute 'sc'

### ISSUE THREAD

**Issue by Marwansha** [davisidarta/topometry#12]
am not sure why i get this error , thanks in advance

```
tg = tp.TopOGraph(base_knn=20, 
                        n_eigs=100, # set this to the largest estimate!
                        n_jobs=-1,
                        verbosity=0)

# Run a TopOMetry model for PBMC3K
adata = tp.sc.topological_workflow(
    adata,                  # the anndata object
    tg,                # the TopOGraph object
    kernels=['bw_adaptive'],# the kernel(s) to use
    eigenmap_methods=['DM'],# the eigenmap method(s) to use
    projections=['MAP'],    # the projection(s) to use
    resolution=0.8          # the Leiden clustering resolution
)
----> 7 adata = tp.sc.topological_workflow(
      8     adata,                  # the anndata object
      9     tg,                # the TopOGraph object
     10     kernels=['bw_adaptive'],# the kernel(s) to use
     11     eigenmap_methods=['DM'],# the eigenmap method(s) to use
     12     projections=['MAP'],    # the projection(s) to use
     13     resolution=0.8          # the Leiden clustering resolution
     14 )

AttributeError: module 'topo' has no attribute 'sc'
```

**Comment by davisidarta** [comment]
This is odd. It could be a bug. 
 
What Python version are you using? Did you install via `pip` or `conda`?

**Comment by Marwansha** [comment]
```
print(python_version())
3.11.4
```

i created a new virutal enviroment and did excatly yhis 

pip install cmake
pip install scikit-build setuptools
pip install --use-pep517 topometry
pip install multicore-tsne umap-learn pacmap trimap pymde ncvis **_scanpy_**

**Comment by Marwansha** [comment]
managed to solve it, pip uninstall scanpy 
then pip install scanpy again and restarting kernel made it work

**Comment by davisidarta** [comment]
I think this is related to your python version. TopOMetry was tested in python versions from ~3.6 to ~3.10. I was unable to reproduce your error using python 3.10.4 in Google Colab: https://colab.research.google.com/drive/1Vw-PXAxLvrqe6zMMS5lHjH8i_ValeRDR?usp=sharing

 I will need to read into it, but it might be possible that python 3.11 doesn't even install the `tp.sc` module if you don't have scanpy before hand, as the functions are defined under the `if has_scanpy` conditional.

Could you please try inverting the order of installations? 
Something like:
```
# In a fresh virtual environment:

pip install cmake
pip install scikit-build setuptools
pip install scanpy
pip install --use-pep517 topometry
```
or 

```
# In your current virtual environment:
pip install -U --use-pep517 topometry
```
Please let me know if this works. If not, you might have to use python 3.10 or we might have to come with another workaround.

**Comment by davisidarta** [comment]
Oh, good to know! I had just hit `Comment` when you replied heheh :)

I'll answer your other questions in the respective issues. Thanks for trying topometry!
